---
- name: Install mysql
  become: yes
  apt:
    name:
      - mysql-server-8.0
      - python3-mysqldb

- name: Start the MySQL service
  become: yes
  action: service name=mysql state=started

- name: Change the authentication plugin of MySQL root user to mysql_native_password
  become: yes
  shell: mysql -u root -e 'UPDATE mysql.user SET plugin="mysql_native_password" WHERE user="root" AND host="localhost"'

- name: Flush Privileges
  become: yes
  shell: mysql -u root -e 'FLUSH PRIVILEGES'

- name: Set MySQL root password
  become: yes
  become_user: root
  mysql_user:
    login_host: "localhost"
    login_user: "root"
    login_password: ""
    priv: "*.*:ALL,GRANT"
    name: "root"
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    state: present
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

# - name: Set root user password
#   become: true
#   become_user: root
#   mysql_user:
#     name: root
#     host: "{{ item }}"
#     password: "{{ mysql_root_password }}"
#     priv: "*.*:ALL,GRANT"
#   with_items:
#     - "{{ ansible_hostname }}"
#     - 127.0.0.1
#     - ::1
#     - localhost

- name: Copy .my.cnf file with root password credentials
  become: true
  become_user: root
  template: src=roles/mysql/templates/.my.cnf dest=/root/.my.cnf owner=root mode=0600

- name: Create mysql user
  become: yes
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "*.*:ALL"

- name: Create mysql database
  become: yes
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present

- name: Delete anonymous MySQL server user for $server_hostname
  become: yes
  action: mysql_user user="" host="{{ server_hostname }}" state="absent"

- name: Delete anonymous MySQL server user for localhost
  become: yes
  action: mysql_user user="" state="absent"

- name: Remove the MySQL test database
  become: yes
  action: mysql_db db=test state=absent

- name: Update mysql root password for all root accounts
  become: yes
  mysql_user:
    name: root
    host: "{{ server_hostname }}"
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
